### ISSUE TITLE
Broken on Manjaro Arch Linux

### ISSUE THREAD

**Issue by xeruf** [Juve45/batstat#13] opened 2024-08-05 16:41 UTC
Apparently the new mechanism intended to fix https://github.com/Juve45/batstat/issues/11 does not work:

![latest master to the left, my old version to the right](https://github.com/user-attachments/assets/94787fb5-b71a-4eb6-835f-3ee634c81f93)

The right working version is my old one from https://github.com/xeruf/batstat introduced after https://github.com/Juve45/batstat/issues/5, to the left the latest master

```sh
❯ sudo ls /sys/class/power_supply/BAT1 | cat
alarm
capacity
capacity_level
charge_full
charge_full_design
charge_now
current_now
cycle_count
device
hwmon2
manufacturer
model_name
power
present
serial_number
status
subsystem
technology
type
uevent
voltage_min_design
voltage_now
```

**Comment by Juve45** [comment] 2024-09-03 15:31
I do not think that version is correct, since it messes up voltage with power. But apparently mine does not work neither. Will try to fix.

Unfortunately I do not have an arch machine to test with these files. Maybe you could post some values from the 
`voltage_now`, `charge_now` and `current_now`?

**Comment by Juve45** [comment] 2024-09-03 21:28
Fixed in the today's commit. However, the fix is not perfect, as conversion to Watt-hour and Watt display from Current, Voltage and Charge reading is not obvious for me at the moment. The problem is the full capacity of the battery. I am unsure if it is ok to compute it with the minimum voltage. Usually, while discharging, it starts with a higher voltage and then it gradually decreases. Using the minimum voltage will result in a smaller capacity.

At the moment, the reading in Ah and A should be correct and consistent (showing the right capacity in Ah, and the discharge current in A)

**Closed as completed by Juve45** 2024-09-03 21:28 UTC

**Comment by xeruf** [comment] 2024-09-04 17:24
working :+1:
